/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projet_onitama;

import java.awt.GridLayout;
import java.awt.List;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.lang.Math.random;
import static java.lang.StrictMath.random;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JButton;
import java.util.Random;

/**
 *
 * @author Gaspard Rouault
 */
public class Fenetre_Principale extends javax.swing.JFrame {

    GrilleDeJeu grille;
    
    /**
     * Creates new form Fenetre_Principale
     */
    public Fenetre_Principale() {
        initComponents();
        this.grille = new GrilleDeJeu(5, 5);
        PanneauGrille.setLayout(new GridLayout(5, 5));
        getContentPane().add(PanneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 5 * 40, 5 * 40));
        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 5; j++) {
                CaseGrilleGraphique bouton_case = new CaseGrilleGraphique(grille.matriceCellules[i][j]);
                PanneauGrille.add(bouton_case); // ajout au Jpanel PanneauGrille
            }
        }
    }
    
    /**
     * Méthode qui tire 5 cartes aléatoirement 
     * @return un arraylist contenant les 5 cartes
     */
    public ArrayList tirerCartesAléatoire() {
        ArrayList<String> tab = new ArrayList<String>();
        tab.add("Boar");
        tab.add("Cobra");
        tab.add("Crab");
        tab.add("Crane");
        tab.add("Dragon");
        tab.add("Eel");
        tab.add("Elephant");
        tab.add("Frog");
        tab.add("Goose");
        tab.add("Horse");
        tab.add("Mantis");
        tab.add("Monkey");
        tab.add("Ox");
        tab.add("Rabbit");
        tab.add("Rooster");
        tab.add("Tiger");
        ArrayList<String> cartes_tirees = new ArrayList<String>();
        Random random = new Random();
        for (int i = 0 ; i<5 ; i++) {
            int temp = random.nextInt(16);
            String carte_temp = tab.get(temp);
            cartes_tirees.add(carte_temp);
            tab.remove(carte_temp);
        }
        return cartes_tirees;
    }
        
        
    
    
    /*public String tirerCarteAleatoire() {
        
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanneauGrille = new javax.swing.JPanel();
        PanneauCarteHautGauche = new javax.swing.JPanel();
        PanneauCarteHautDroite = new javax.swing.JPanel();
        PanneauCarteBasGauche = new javax.swing.JPanel();
        PanneauCarteBasDroite = new javax.swing.JPanel();
        PanneauCarteGauche = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanneauGrille.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout PanneauGrilleLayout = new javax.swing.GroupLayout(PanneauGrille);
        PanneauGrille.setLayout(PanneauGrilleLayout);
        PanneauGrilleLayout.setHorizontalGroup(
            PanneauGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        PanneauGrilleLayout.setVerticalGroup(
            PanneauGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 211, Short.MAX_VALUE)
        );

        PanneauCarteHautGauche.setBackground(new java.awt.Color(204, 204, 255));
        PanneauCarteHautGauche.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout PanneauCarteHautGaucheLayout = new javax.swing.GroupLayout(PanneauCarteHautGauche);
        PanneauCarteHautGauche.setLayout(PanneauCarteHautGaucheLayout);
        PanneauCarteHautGaucheLayout.setHorizontalGroup(
            PanneauCarteHautGaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );
        PanneauCarteHautGaucheLayout.setVerticalGroup(
            PanneauCarteHautGaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );

        PanneauCarteHautDroite.setBackground(new java.awt.Color(204, 204, 255));
        PanneauCarteHautDroite.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanneauCarteHautDroite.setPreferredSize(new java.awt.Dimension(88, 88));

        javax.swing.GroupLayout PanneauCarteHautDroiteLayout = new javax.swing.GroupLayout(PanneauCarteHautDroite);
        PanneauCarteHautDroite.setLayout(PanneauCarteHautDroiteLayout);
        PanneauCarteHautDroiteLayout.setHorizontalGroup(
            PanneauCarteHautDroiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );
        PanneauCarteHautDroiteLayout.setVerticalGroup(
            PanneauCarteHautDroiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );

        PanneauCarteBasGauche.setBackground(new java.awt.Color(204, 204, 255));
        PanneauCarteBasGauche.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanneauCarteBasGauche.setPreferredSize(new java.awt.Dimension(88, 88));

        javax.swing.GroupLayout PanneauCarteBasGaucheLayout = new javax.swing.GroupLayout(PanneauCarteBasGauche);
        PanneauCarteBasGauche.setLayout(PanneauCarteBasGaucheLayout);
        PanneauCarteBasGaucheLayout.setHorizontalGroup(
            PanneauCarteBasGaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );
        PanneauCarteBasGaucheLayout.setVerticalGroup(
            PanneauCarteBasGaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );

        PanneauCarteBasDroite.setBackground(new java.awt.Color(204, 204, 255));
        PanneauCarteBasDroite.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanneauCarteBasDroite.setPreferredSize(new java.awt.Dimension(88, 88));

        javax.swing.GroupLayout PanneauCarteBasDroiteLayout = new javax.swing.GroupLayout(PanneauCarteBasDroite);
        PanneauCarteBasDroite.setLayout(PanneauCarteBasDroiteLayout);
        PanneauCarteBasDroiteLayout.setHorizontalGroup(
            PanneauCarteBasDroiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );
        PanneauCarteBasDroiteLayout.setVerticalGroup(
            PanneauCarteBasDroiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );

        PanneauCarteGauche.setBackground(new java.awt.Color(204, 204, 255));
        PanneauCarteGauche.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanneauCarteGauche.setPreferredSize(new java.awt.Dimension(88, 88));

        javax.swing.GroupLayout PanneauCarteGaucheLayout = new javax.swing.GroupLayout(PanneauCarteGauche);
        PanneauCarteGauche.setLayout(PanneauCarteGaucheLayout);
        PanneauCarteGaucheLayout.setHorizontalGroup(
            PanneauCarteGaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );
        PanneauCarteGaucheLayout.setVerticalGroup(
            PanneauCarteGaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(PanneauCarteGauche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanneauCarteBasGauche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PanneauCarteBasDroite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(PanneauCarteHautGauche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PanneauCarteHautDroite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PanneauGrille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(240, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanneauCarteHautDroite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanneauCarteHautGauche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(PanneauGrille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(PanneauCarteGauche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanneauCarteBasGauche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanneauCarteBasDroite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenetre_Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenetre_Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenetre_Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetre_Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fenetre_Principale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanneauCarteBasDroite;
    private javax.swing.JPanel PanneauCarteBasGauche;
    private javax.swing.JPanel PanneauCarteGauche;
    private javax.swing.JPanel PanneauCarteHautDroite;
    private javax.swing.JPanel PanneauCarteHautGauche;
    private javax.swing.JPanel PanneauGrille;
    // End of variables declaration//GEN-END:variables
}
